import type { AppData } from './types'

export const defaultData: AppData = {
  version: 15,
  categories: [],
  snippets: [],
  templates: [],
  taskTemplates: [],
  procedures: [],
  notes: '',
  emailDraft: '',
  taskDraft: '',
  history: [],
  callHistory: [],
  settings: {
    language: 'fr',
    zoom: 1,
    textScale: 1,
    editorLineHeight: 1.6,
    exportFont: 'Calibri, "Segoe UI", Arial, sans-serif',
    exportFontSize: 12,
    historyOnCopy: true,
    historyLimit: 200,
    callTemplate: '',
    autoFocusEditor: true,
    defaultSnippetInsertMode: 'line',
    snippetCategoryDisplay: 'dropdown',
    quickLinkUrls: {
      crm: '',
      share: '',
      global: '',
      portal: '',
      assist: '',
    },
    predefinedTags: [],
    customerPortalCodes: [],
    dashboardProducts: [],
    products: [],
    dashboardNews: [],
    dashboardProcessLines: [],
  },
}
