import type { AppData } from './types'

export const defaultData: AppData = {
  version: 23,
  categories: [],
  snippets: [],
  templates: [],
  taskTemplates: [],
  procedures: [],
  notes: '',
  emailDraft: '',
  taskDraft: '',
  history: [],
  callHistory: [],
  settings: {
    language: 'fr',
    zoom: 1,
    textScale: 1,
    editorLineHeight: 1.6,
    exportFont: 'Calibri, "Segoe UI", Arial, sans-serif',
    exportFontSize: 12,
    historyOnCopy: true,
    historyLimit: 200,
    callTemplate: '',
    autoFocusEditor: true,
    defaultSnippetInsertMode: 'line',
    snippetCategoryDisplay: 'dropdown',
    quickLinkUrls: {
      crm: '',
      share: '',
      global: '',
      portal: '',
      assist: '',
    },
    procedureMailtoLinks: [
      {
        id: 'mailto-support',
        label: 'Support',
        to: 'support@example.com',
        subject: 'Demande de support',
        body: 'Bonjour,\n\nJe vous contacte au sujet de...',
      },
      {
        id: 'mailto-sav',
        label: 'SAV',
        to: 'sav@example.com',
        subject: 'Suivi SAV',
        body: 'Bonjour,\n\nPouvez-vous faire le point sur...',
      },
    ],
    predefinedTags: [],
    customerPortalCodes: [],
    dashboardProcessSettings: [
      {
        id: 'rma-14',
        rush: false,
        completeProcedureId: '',
        reducedProcedureId: '',
      },
      {
        id: 'rma-30',
        rush: false,
        completeProcedureId: '',
        reducedProcedureId: '',
      },
    ],
    dashboardProducts: [],
    products: [
      {
        id: 'sample-troubleshootgun-product',
        name: 'Pack vérification Troubleshootgun',
        productType: 'Demo',
        note: 'Produit seed pour valider l’aperçu Troubleshootgun.',
        tags: ['demo', 'email', 'test'],
        packingGuideAvailable: false,
        compatibleProductIds: [],
        softwareIds: [],
        driverIds: [],
        firmwareIds: [],
        editions: [],
        spareParts: [],
        troubleshootgunTemplates: [
          {
            id: 'sample-troubleshootgun-template-1',
            name: 'Email entrant',
            content:
              'Objet: Problème de connexion\n\nBonjour,\n\nJe n’arrive plus à me connecter à mon compte depuis ce matin. Pouvez-vous vérifier ?\n\nMerci.',
            taskText: 'Répondre avec la procédure de réinitialisation du mot de passe.',
          },
          {
            id: 'sample-troubleshootgun-template-2',
            name: 'Relance client',
            content:
              'Objet: Relance dossier SAV\n\nBonjour,\n\nJe reviens vers vous concernant mon ticket. Avez-vous une mise à jour ?\n\nCordialement,',
            taskText: 'Confirmer le statut du ticket et proposer un délai.',
          },
          {
            id: 'sample-troubleshootgun-template-3',
            name: 'Clôture',
            content:
              'Objet: Ticket résolu\n\nBonjour,\n\nLe problème est maintenant résolu. Merci pour votre aide et votre réactivité.\n\nBien à vous,',
            taskText: 'Clôturer le ticket et archiver la réponse modèle.',
          },
        ],
      },
    ],
    dashboardNews: [],
    dashboardReminders: '',
  },
}
