import type { AppIconName } from '../lib/iconTypes'
import {
  AppWindow,
  Archive,
  Book,
  CircleDollarSign,
  ClipboardList,
  Download,
  Equal,
  FileText,
  Folder,
  FolderOpen,
  GitBranch,
  Hammer,
  History,
  Inbox,
  Info,
  LayoutDashboard,
  LayoutGrid,
  Layers,
  Link,
  List,
  Mail,
  Monitor,
  MonitorCog,
  Newspaper,
  Package,
  Pencil,
  Phone,
  Plus,
  Save,
  Search,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  SquareTerminal,
  StickyNote,
  Tag,
  Trash2,
  Warehouse,
  Wrench,
  X,
  type LucideIcon,
} from 'lucide-react'

/* Set d'icônes Lucide (successeur maintenu de Feather) — un seul style de
   trait pour toute l'app. Les quick links (configurables par l'utilisateur)
   restent des images et ne passent pas par ici. */
const icons: Record<AppIconName, LucideIcon> = {
  add: Plus,
  archive: Archive,
  asciiWall: SquareTerminal,
  screenEmulator: MonitorCog,
  book: Book,
  box: Package,
  call: Phone,
  channels: Layers,
  close: X,
  dashboard: LayoutDashboard,
  delete: Trash2,
  display: Monitor,
  download: Download,
  edit: Pencil,
  exchange: Equal,
  folder: Folder,
  folderOpen: FolderOpen,
  grid: LayoutGrid,
  hangar: Warehouse,
  history: History,
  inbox: Inbox,
  info: Info,
  link: Link,
  list: List,
  mail: Mail,
  maintenance: Wrench,
  money: CircleDollarSign,
  news: Newspaper,
  notes: StickyNote,
  phone: Phone,
  portal: AppWindow,
  preferences: SlidersHorizontal,
  save: Save,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  systemReport: ClipboardList,
  tag: Tag,
  template: FileText,
  tool: Hammer,
  version: GitBranch,
}

export const UiIcon = ({ name, className }: { name: AppIconName; className?: string }) => {
  const Icon = icons[name]
  /* size = défaut quand aucune classe ne dimensionne (sinon Lucide rend 24px) ;
     les règles CSS width/height priment toujours sur l'attribut */
  return <Icon aria-hidden className={className} strokeWidth={1.75} size={14} />
}
